const fs = require('fs');
const path = require('path');
const { expect } = require('chai');

describe('generated output identity', () => {
  const repoRoot = path.resolve(__dirname, '..');

  function read(relativePath) {
    return fs.readFileSync(path.join(repoRoot, relativePath), 'utf8');
  }

  it('uses Archscope in PR comment and issue template prose', () => {
    const prCommentWorkflow = read('.github/workflows/pr-impact-comment.yml');
    const featureTemplate = read('.github/ISSUE_TEMPLATE/feature.yml');
    const issueTemplate = read('.github/ISSUE_TEMPLATE/issue.yml');

    expect(prCommentWorkflow).to.include('Generated by [Archscope](https://github.com/jscraik/diagram-cli)');
    expect(prCommentWorkflow).to.not.include('Generated by [diagram-cli]');

    expect(featureTemplate).to.include('How should the Archscope command, format, or rule behavior work?');
    expect(featureTemplate).to.not.include('diagram-cli command/format/rule behavior');

    expect(issueTemplate).to.include('failing archscope command; diagram remains a compatibility alias');
    expect(issueTemplate).to.not.include('failing diagram command');
  });

  it('keeps generated next-step guidance Archscope-first', () => {
    const sourcePaths = [
      'src/commands/analyze.js',
      'src/commands/changed.js',
      'src/commands/context.js',
      'src/commands/doctor.js',
      'src/commands/explain.js',
      'src/commands/generate-all.js',
      'src/commands/generate.js',
      'src/commands/generate-animated.js',
      'src/commands/generate-video.js',
      'src/commands/validate.js',
      'src/workflow/pr-command.js',
    ];
    const combined = sourcePaths.map(read).join('\n');

    expect(combined).to.include('archscope workflow pr');
    expect(combined).to.include('archscope validate');
    expect(combined).to.include('archscope generate-all');
    expect(combined).to.include('archscope context');
    expect(combined).to.not.match(/Run `diagram (validate|workflow|generate|generate-all|context|doctor|changed)/);
    expect(combined).to.not.match(/Use `diagram (workflow|explain)/);
    expect(combined).to.not.match(/Re-run `diagram workflow pr/);
  });
});
