#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd -P)"

cd "$REPO_ROOT"

if ! git rev-parse --show-toplevel >/dev/null 2>&1; then
	echo "Error: scripts/check-prek-hooks.sh must run inside a git worktree"
	exit 1
fi

required_hooks=("pre-commit" "pre-push" "commit-msg")
expected_home='PREK_HOME="${PREK_HOME:-$HERE/../.cache/prek}"'

for hook_name in "${required_hooks[@]}"; do
	hook_path="$(git rev-parse --git-path "hooks/${hook_name}")"
	if [[ ! -f "$hook_path" ]]; then
		continue
	fi

	if ! rg -q "File generated by prek" "$hook_path"; then
		continue
	fi

	if ! rg -Fq "$expected_home" "$hook_path"; then
		echo "Error: ${hook_path} is a prek hook but does not set repo-local PREK_HOME"
		echo "Expected hook line:"
		printf '%s\n' "  $expected_home"
		echo "Fix: run 'make hooks' or 'node scripts/setup-git-hooks.js' from the repo root."
		exit 1
	fi

	if ! rg -q '^[[:space:]]*export PREK_HOME[[:space:]]*$' "$hook_path"; then
		echo "Error: ${hook_path} sets PREK_HOME but does not export it before invoking prek"
		echo "Fix: run 'make hooks' or 'node scripts/setup-git-hooks.js' from the repo root."
		exit 1
	fi
done
