#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
CONTRACT_PATH="$REPO_ROOT/docs/agents/tooling.contract.json"
OUTPUT_PATH="$REPO_ROOT/docs/agents/tooling.md"

if [[ ! -f "$CONTRACT_PATH" ]]; then
  echo "Error: missing tooling contract at $CONTRACT_PATH"
  exit 1
fi

jq -e '
  (.required_mise_tools | type == "array" and length > 0) and
  (.required_bins | type == "array" and length > 0) and
  (.required_codex_actions | type == "array" and length > 0)
' "$CONTRACT_PATH" >/dev/null

{
  cat <<'EOF'
# Project Tooling Inventory

## Table of Contents
- [Source of truth](#source-of-truth)
- [Required Mise Tools](#required-mise-tools)
- [Required Binaries](#required-binaries)
- [Required Codex Actions](#required-codex-actions)

## Source of truth
This file is generated from `docs/agents/tooling.contract.json`.
Do not edit this file manually. Regenerate it with:
`bash scripts/render-tooling-doc.sh`

## Required Mise Tools
EOF

  jq -r '.required_mise_tools[] | "- `\(.)`"' "$CONTRACT_PATH"

  cat <<'EOF'

## Required Binaries
EOF

  jq -r '.required_bins[] | "- `\(.)`"' "$CONTRACT_PATH"

  cat <<'EOF'

## Required Codex Actions
EOF

  jq -r '.required_codex_actions[] | "- `\(.name)` (`\(.icon)`)"' "$CONTRACT_PATH"
} > "$OUTPUT_PATH"

echo "Wrote $OUTPUT_PATH"
