graph LR
  path_a0af9f86["path"] --> setup_8fb6d5f3
  chai_ca9cfcfa["chai"] --> setup_8fb6d5f3
  chai_ca9cfcfa["chai"] --> rules_test_055a2615
  rules_test_055a2615 --> import_rule_641ce46a
  chai_ca9cfcfa["chai"] --> rules_inward_only_test_8e19a333
  rules_inward_only_test_8e19a333 --> import_rule_641ce46a
  rules_inward_only_test_8e19a333 --> factory_06c8aaa9
  rules_inward_only_test_8e19a333 --> rules_6c621d1a
  rules_inward_only_test_8e19a333 --> rules_schema_1b0ae367
  rules_inward_only_test_8e19a333 --> rules_schema_1b0ae367
  rules_inward_only_test_8e19a333 --> rules_schema_1b0ae367
  assert_25450689["assert"] --> pr_impact_test_66267a43
  pr_impact_test_66267a43 --> diagram_2c20a6b0
  chai_ca9cfcfa["chai"] --> confidence_test_eed6c8ab
  confidence_test_eed6c8ab --> pipeline_23bf0d24
  confidence_test_eed6c8ab --> architecture_ir_78febc36
  confidence_test_eed6c8ab --> cache_5e1ecee0
  playwright_7827e8eb["playwright"] --> video_0cab1c96
  fs_dce7cce0["fs"] --> video_0cab1c96
  path_a0af9f86["path"] --> video_0cab1c96
  os_840a8dcf["os"] --> video_0cab1c96
  crypto_da2f073e["crypto"] --> video_0cab1c96
  child_process_f2d8255a["child_process"] --> video_0cab1c96
  url_28e5ebab["url"] --> video_0cab1c96
  chalk_c886ff11["chalk"] --> video_0cab1c96
  video_0cab1c96 --> commands_10f5f77e
  yaml_9831daaa["yaml"] --> rules_6c621d1a
  fs_dce7cce0["fs"] --> rules_6c621d1a
  path_a0af9f86["path"] --> rules_6c621d1a
  picomatch_0bf97c7b["picomatch"] --> rules_6c621d1a
  commander_fc2dff6a["commander"] --> diagram_2c20a6b0
  fs_dce7cce0["fs"] --> diagram_2c20a6b0
  path_a0af9f86["path"] --> diagram_2c20a6b0
  chalk_c886ff11["chalk"] --> diagram_2c20a6b0
  child_process_f2d8255a["child_process"] --> diagram_2c20a6b0
  os_840a8dcf["os"] --> diagram_2c20a6b0
  crypto_da2f073e["crypto"] --> diagram_2c20a6b0
  zlib_0ea55c28["zlib"] --> diagram_2c20a6b0
  diagram_2c20a6b0 --> commands_10f5f77e
  diagram_2c20a6b0 --> index_1bc04b52
  diagram_2c20a6b0 --> architecture_ir_78febc36
  diagram_2c20a6b0 --> pipeline_23bf0d24
  diagram_2c20a6b0 --> cache_5e1ecee0
  diagram_2c20a6b0 --> analysis_generation_b5695ac7
  diagram_2c20a6b0 --> pr_impact_d40dc5b4
  diagram_2c20a6b0 --> git_helpers_a3a6b8d4
  diagram_2c20a6b0 --> pr_command_8b1c5f2a
  diagram_2c20a6b0 --> diagramrc_0e4f28e4
  diagram_2c20a6b0 --> video_0cab1c96
  diagram_2c20a6b0 --> rules_6c621d1a
  diagram_2c20a6b0 --> graph_eef93e1d
  diagram_2c20a6b0 --> factory_06c8aaa9
  diagram_2c20a6b0 --> index_1_faebc14e
  diagram_2c20a6b0 --> rules_schema_1b0ae367
  yaml_9831daaa["yaml"] --> diagram_2c20a6b0
  yaml_9831daaa["yaml"] --> diagram_2c20a6b0
  node_child_process_cb73900b["node:child_process"] --> validate_commit_msg_43b008fe
  node_fs_df6b52af["node:fs"] --> validate_commit_msg_43b008fe
  node_fs_df6b52af["node:fs"] --> setup_git_hooks_70750d40
  node_path_0e7d56ab["node:path"] --> setup_git_hooks_70750d40
  node_child_process_cb73900b["node:child_process"] --> setup_git_hooks_70750d40
  assert_25450689["assert"] --> deep_regression_4f028409
  fs_dce7cce0["fs"] --> deep_regression_4f028409
  os_840a8dcf["os"] --> deep_regression_4f028409
  path_a0af9f86["path"] --> deep_regression_4f028409
  child_process_f2d8255a["child_process"] --> deep_regression_4f028409
  deep_regression_4f028409 --> commands_10f5f77e
  eventemitter3_ab333bf7["eventemitter3"] --> deep_regression_4f028409
  jsonwebtoken_44701fc5["jsonwebtoken"] --> deep_regression_4f028409
  fs_dce7cce0["fs"] --> pr_impact_d40dc5b4
  path_a0af9f86["path"] --> pr_impact_d40dc5b4
  fs_dce7cce0["fs"] --> pr_command_8b1c5f2a
  path_a0af9f86["path"] --> pr_command_8b1c5f2a
  chalk_c886ff11["chalk"] --> pr_command_8b1c5f2a
  pr_command_8b1c5f2a --> pr_impact_d40dc5b4
  pr_command_8b1c5f2a --> git_helpers_a3a6b8d4
  pr_command_8b1c5f2a --> pipeline_23bf0d24
  commander_fc2dff6a["commander"] --> pr_command_8b1c5f2a
  fs_dce7cce0["fs"] --> git_helpers_a3a6b8d4
  path_a0af9f86["path"] --> git_helpers_a3a6b8d4
  chalk_c886ff11["chalk"] --> git_helpers_a3a6b8d4
  child_process_f2d8255a["child_process"] --> git_helpers_a3a6b8d4
  picomatch_0bf97c7b["picomatch"] --> git_helpers_a3a6b8d4
  git_helpers_a3a6b8d4 --> analysis_generation_b5695ac7
  os_840a8dcf["os"] --> commands_10f5f77e
  path_a0af9f86["path"] --> commands_10f5f77e
  zod_4f63cf5c["zod"] --> rules_schema_1b0ae367
  factory_06c8aaa9 --> import_rule_641ce46a
  fs_dce7cce0["fs"] --> architecture_ir_78febc36
  path_a0af9f86["path"] --> architecture_ir_78febc36
  fs_dce7cce0["fs"] --> cache_5e1ecee0
  path_a0af9f86["path"] --> cache_5e1ecee0
  crypto_da2f073e["crypto"] --> cache_5e1ecee0
  fs_dce7cce0["fs"] --> analysis_generation_b5695ac7
  path_a0af9f86["path"] --> analysis_generation_b5695ac7
  glob_28c2dec1["glob"] --> analysis_generation_b5695ac7
  chalk_c886ff11["chalk"] --> analysis_generation_b5695ac7
  crypto_da2f073e["crypto"] --> analysis_generation_b5695ac7
  fs_dce7cce0["fs"] --> pipeline_23bf0d24
  path_a0af9f86["path"] --> pipeline_23bf0d24
  child_process_f2d8255a["child_process"] --> pipeline_23bf0d24
  pipeline_23bf0d24 --> commands_10f5f77e
  fs_dce7cce0["fs"] --> diagramrc_0e4f28e4
  path_a0af9f86["path"] --> diagramrc_0e4f28e4
  zod_4f63cf5c["zod"] --> diagramrc_0e4f28e4
  index_1bc04b52 --> default_analyzer_abd381a4
  default_analyzer_abd381a4 --> analysis_generation_b5695ac7
  fs_dce7cce0["fs"] --> junit_018bb207
  path_a0af9f86["path"] --> junit_018bb207
  fs_dce7cce0["fs"] --> json_02bd175f
  path_a0af9f86["path"] --> json_02bd175f
  index_1_faebc14e --> console_93d8874c
  index_1_faebc14e --> json_02bd175f
  index_1_faebc14e --> junit_018bb207
  chalk_c886ff11["chalk"] --> console_93d8874c
  import_rule_641ce46a --> base_cae66217
  path_a0af9f86["path"] --> import_rule_641ce46a
  picomatch_0bf97c7b["picomatch"] --> import_rule_641ce46a
  style path_a0af9f86 fill:#f59e0b,color:#fff
  style chai_ca9cfcfa fill:#f59e0b,color:#fff
  style assert_25450689 fill:#f59e0b,color:#fff
  style playwright_7827e8eb fill:#f59e0b,color:#fff
  style fs_dce7cce0 fill:#f59e0b,color:#fff
  style os_840a8dcf fill:#f59e0b,color:#fff
  style crypto_da2f073e fill:#f59e0b,color:#fff
  style child_process_f2d8255a fill:#f59e0b,color:#fff
  style url_28e5ebab fill:#f59e0b,color:#fff
  style chalk_c886ff11 fill:#f59e0b,color:#fff
  style yaml_9831daaa fill:#f59e0b,color:#fff
  style picomatch_0bf97c7b fill:#f59e0b,color:#fff
  style commander_fc2dff6a fill:#f59e0b,color:#fff
  style zlib_0ea55c28 fill:#f59e0b,color:#fff
  style node_child_process_cb73900b fill:#f59e0b,color:#fff
  style node_fs_df6b52af fill:#f59e0b,color:#fff
  style node_path_0e7d56ab fill:#f59e0b,color:#fff
  style eventemitter3_ab333bf7 fill:#f59e0b,color:#fff
  style jsonwebtoken_44701fc5 fill:#f59e0b,color:#fff
  style zod_4f63cf5c fill:#f59e0b,color:#fff
  style glob_28c2dec1 fill:#f59e0b,color:#fff